Update sync.yml

diff --git a/.github/workflows/sync.yml b/.github/workflows/sync.yml
--- a/.github/workflows/sync.yml
+++ b/.github/workflows/sync.yml
@@ -1,26 +1,34 @@
-name: Sync Fork
+name: Sync Upstream
 
-on:
+permissions: write-all              # 授予写权限
+
+on: 
   schedule:
-    - cron: '0 2 * * *'  # 每日凌晨2点触发
-  workflow_dispatch: # 允许手动触发工作流
+    - cron: '0 2 * * *'             # 每日凌晨2点触发
+  workflow_dispatch:                # 允许手动触发工作流
 
 jobs:
-  sync:
+  sync-upstream:
     runs-on: ubuntu-latest
-    
-    steps:
-    - name: Checkout repo
-      uses: actions/checkout@v3
-      with:
-        ref: main # 这里填写你的主要分支名称
+    steps: 
+      - name: Checkout
+        uses: actions/checkout@v3
 
-    - name: Sync with upstream
-      run: |
-        git remote add upstream https://github.com/LeeYouRan/linux.do-bot.git
-        git fetch upstream
-        git checkout main
-        git merge upstream/main
-        git push origin main
-      env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      - name: Sync upstream changes
+        id: sync
+        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
+        with:
+            # 所需的“target_repo_token”与此完全相同！
+            target_repo_token: ${{ secrets.GITHUB_TOKEN }}
+            target_sync_branch: main
+            upstream_sync_branch: main
+            upstream_sync_repo: LeeYouRan/linux.do-bot
+
+            # 在手动调度期间将 test_mode 设置为 true 来运行测试而不是 true 操作！！
+            test_mode: false
+
+      - name: Sync check
+        if: failure()
+        run: |
+          echo "[Error] 由于上游仓库的 workflow 文件变更，导致 GitHub 自动暂停了本次自动更新，你需要手动 Sync Fork 一次。"
+          exit 1
